# Site settings
title: 半步运维人
tagline:  运维半生，归来仍是少年
email: damonops@163.com
description: personal blog, record my work and life, happy or sad
baseurl: ""
github_username: Half-SRE
paginate:     1
locale:       "en"
author:
  name:       Damon
  url:        https://halfsre.com

gems:
  - jekyll-paginate
# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

